-- =====================================================================
-- Admin alerts — generated by the scheduled scanner; one row per fired
-- condition. Dedupe key prevents the same alert firing repeatedly.
-- =====================================================================

CREATE TABLE alerts (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    rule_id         VARCHAR(40)  NOT NULL,
    severity        VARCHAR(16)  NOT NULL DEFAULT 'INFO',
    title           VARCHAR(200) NOT NULL,
    message         TEXT         NOT NULL,
    payload         MEDIUMTEXT   NULL,
    dedupe_key      VARCHAR(120) NOT NULL,
    read_flag       TINYINT(1)   NOT NULL DEFAULT 0,
    email_sent      TINYINT(1)   NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_alerts_dedupe (dedupe_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX idx_alerts_read_created  ON alerts(read_flag, created_at DESC);
CREATE INDEX idx_alerts_rule          ON alerts(rule_id, created_at);
